export type VideoSourceType = "youtube" | "mp4" | "embed";

export type ClinicVideo = {
  id: string;
  category: "疾病認識" | "急性惡化" | "吸入劑" | "營養照護" | "肺復原" | "氧氣治療";
  title: string;
  src: string;
  type: VideoSourceType;
  durationSeconds: number;
  durationNote?: string;
};

export type PlaylistProgram = {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  rounds?: number;
  videoIds: string[];
};

export const TARGET_PROGRAM_SECONDS = 90 * 60;
export const DEFAULT_CLINIC_SESSION_ROUNDS = 2;

export const videos: ClinicVideo[] = [
  {
    id: "disease-overview",
    category: "疾病認識",
    title: "肺阻塞教學影片",
    src: "https://www.youtube.com/embed/vv9AZ9U2iZI",
    type: "youtube",
    durationSeconds: 4 * 60 + 48,
    durationNote: "實際片長 4:48",
  },
  {
    id: "acute-exacerbation",
    category: "急性惡化",
    title: "急性惡化教學影片",
    src: "https://www.youtube.com/embed/XIgI8DaCWdg",
    type: "youtube",
    durationSeconds: 4 * 60 + 5,
    durationNote: "實際片長 4:05",
  },
  {
    id: "respimat-load",
    category: "吸入劑",
    title: "舒沛噴吸入劑裝填方式",
    src: "https://media.ntuh.gov.tw/media/e/857",
    type: "embed",
    durationSeconds: 1 * 60 + 21,
    durationNote: "實際片長 1:21",
  },
  {
    id: "respimat-use",
    category: "吸入劑",
    title: "舒沛噴吸入劑使用方式",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663374529761/fdzmElOyFOHjAYeb.mp4",
    type: "mp4",
    durationSeconds: 3 * 60 + 29,
    durationNote: "實際片長 3:29",
  },
  {
    id: "respimat-spacer",
    category: "吸入劑",
    title: "舒沛噴吸入劑加口含式吸藥輔助器",
    src: "https://media.ntuh.gov.tw/media/e/869",
    type: "embed",
    durationSeconds: 2 * 60 + 19,
    durationNote: "實際片長 2:19",
  },
  {
    id: "berotec-mdi",
    category: "吸入劑",
    title: "備勞喘定量噴霧吸入劑使用方式",
    src: "https://media.ntuh.gov.tw/media/e/862",
    type: "embed",
    durationSeconds: 1 * 60 + 48,
    durationNote: "實際片長 1:48",
  },
  {
    id: "bevespi",
    category: "吸入劑",
    title: "必肺宜 Bevespi 使用方式",
    src: "https://www.youtube.com/embed/RSAHSGxYY90",
    type: "youtube",
    durationSeconds: 2 * 60 + 4,
    durationNote: "實際片長 2:04",
  },
  {
    id: "seretide-mdi",
    category: "吸入劑",
    title: "使肺泰定量噴霧吸入劑使用方式",
    src: "https://media.ntuh.gov.tw/media/e/865",
    type: "embed",
    durationSeconds: 3 * 60,
    durationNote: "估計值",
  },
  {
    id: "symbicort-mdi",
    category: "吸入劑",
    title: "吸必擴定量噴霧吸入劑使用方式",
    src: "https://media.ntuh.gov.tw/media/e/859",
    type: "embed",
    durationSeconds: 3 * 60,
    durationNote: "估計值",
  },
  {
    id: "seretide-mask-spacer",
    category: "吸入劑",
    title: "使肺泰加面罩式吸藥輔助器",
    src: "https://media.ntuh.gov.tw/media/e/865",
    type: "embed",
    durationSeconds: 4 * 60,
    durationNote: "估計值；與使肺泰影片來源相同，請日後確認是否需替換",
  },
  {
    id: "seretide-mouthpiece-spacer",
    category: "吸入劑",
    title: "使肺泰加口含式吸藥輔助器",
    src: "https://media.ntuh.gov.tw/media/e/868",
    type: "embed",
    durationSeconds: 4 * 60,
    durationNote: "估計值",
  },
  {
    id: "trimbow",
    category: "吸入劑",
    title: "喘寶 Trimbow 使用方式",
    src: "https://www.youtube.com/embed/HKaFFVkprfM",
    type: "youtube",
    durationSeconds: 4 * 60,
    durationNote: "估計值",
  },
  {
    id: "breztri",
    category: "吸入劑",
    title: "必肺暢 Breztri 使用方式",
    src: "https://www.youtube.com/embed/Y_Jb_KhBmSU",
    type: "youtube",
    durationSeconds: 4 * 60,
    durationNote: "估計值",
  },
  {
    id: "trelegy",
    category: "吸入劑",
    title: "肺樂喜 Trelegy 使用方式",
    src: "https://www.youtube.com/embed/-NKvp1AjpVg",
    type: "youtube",
    durationSeconds: 4 * 60,
    durationNote: "估計值",
  },
  {
    id: "relvar",
    category: "吸入劑",
    title: "潤娃 Relvar 使用方式",
    src: "https://media.ntuh.gov.tw/media/e/871",
    type: "embed",
    durationSeconds: 4 * 60,
    durationNote: "估計值",
  },
  {
    id: "anoro",
    category: "吸入劑",
    title: "安肺樂 Anoro 使用方式",
    src: "https://drive.google.com/file/d/1gN9tUbjwndWDD4DBiBpNPziXPkYk2TVv/preview",
    type: "embed",
    durationSeconds: 4 * 60,
    durationNote: "估計值",
  },
  {
    id: "ultibro",
    category: "吸入劑",
    title: "昂帝博 Ultibro 使用方式",
    src: "https://drive.google.com/file/d/1ccC-xynG8IfAlAwkZAC2kBkIECevH6-9/preview",
    type: "embed",
    durationSeconds: 4 * 60,
    durationNote: "估計值",
  },
  {
    id: "spacer-cleaning",
    category: "吸入劑",
    title: "吸藥輔助器的清洗方式",
    src: "https://media.ntuh.gov.tw/media/e/1069",
    type: "embed",
    durationSeconds: 5 * 60,
    durationNote: "估計值",
  },
  {
    id: "nutrition-lung",
    category: "營養照護",
    title: "Lung 你吃對營養 COPD 營養照護",
    src: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663374529761/VHLuPTGqTLqhWdrt.mp4",
    type: "mp4",
    durationSeconds: 18 * 60 + 28,
    durationNote: "實際片長 18:28",
  },
  {
    id: "nutrition-taiwanese",
    category: "營養照護",
    title: "肺阻塞的營養照護 林明憲（台語）",
    src: "https://www.youtube.com/embed/_IVVH0Ajkxc",
    type: "youtube",
    durationSeconds: 18 * 60,
    durationNote: "估計值",
  },
  {
    id: "airway-clearance",
    category: "肺復原",
    title: "呼吸道痰液清除方法",
    src: "https://www.youtube.com/embed/vq1yjbj4_G4",
    type: "youtube",
    durationSeconds: 5 * 60 + 6,
    durationNote: "實際片長 5:06",
  },
  {
    id: "diaphragmatic-breathing",
    category: "肺復原",
    title: "腹式呼吸教學",
    src: "https://www.youtube.com/embed/g2nsbUEZOQQ",
    type: "youtube",
    durationSeconds: 2 * 60 + 42,
    durationNote: "實際片長 2:42",
  },
  {
    id: "resistance-band",
    category: "肺復原",
    title: "彈力帶運動",
    src: "https://www.youtube.com/embed/agSzsr7cQAc",
    type: "youtube",
    durationSeconds: 8 * 60,
    durationNote: "估計值",
  },
  {
    id: "chest-expansion",
    category: "肺復原",
    title: "擴胸運動",
    src: "https://www.youtube.com/embed/nR8KNsXrses",
    type: "youtube",
    durationSeconds: 6 * 60,
    durationNote: "估計值",
  },
  {
    id: "pulmonary-rehab",
    category: "肺復原",
    title: "肺部復健運動",
    src: "https://www.youtube.com/embed/kQDkuZnWtUc",
    type: "youtube",
    durationSeconds: 3 * 60 + 22,
    durationNote: "實際片長 3:22",
  },
  {
    id: "oxygen-equipment",
    category: "氧氣治療",
    title: "氧氣設備操作教學",
    src: "https://www.youtube.com/embed/Af5pNzaub5g",
    type: "youtube",
    durationSeconds: 3 * 60 + 55,
    durationNote: "實際片長 3:55",
  },
];

export const programs: PlaylistProgram[] = [
  {
    id: "program-a",
    title: "組合 A：基礎認識與常見吸入劑",
    subtitle: "適合上午診開場，先建立疾病觀念，再穿插 5 種常見吸入劑示範。",
    description: "疾病認識、急性惡化、舒沛噴、備勞喘、必肺宜、營養與肺復原。",
    rounds: 3,
    videoIds: [
      "disease-overview",
      "respimat-load",
      "respimat-use",
      "respimat-spacer",
      "acute-exacerbation",
      "berotec-mdi",
      "bevespi",
      "nutrition-lung",
      "diaphragmatic-breathing",
      "airway-clearance",
      "pulmonary-rehab",
      "oxygen-equipment",
    ],
  },
  {
    id: "program-b",
    title: "組合 B：急性警訊與定量噴霧吸入劑",
    subtitle: "適合人潮較多時段，反覆提醒急性惡化警訊與吸藥技巧。",
    description: "急性惡化、使肺泰、吸必擴、喘寶、輔助器清潔、營養與運動。",
    videoIds: [
      "acute-exacerbation",
      "seretide-mdi",
      "symbicort-mdi",
      "seretide-mask-spacer",
      "seretide-mouthpiece-spacer",
      "trimbow",
      "spacer-cleaning",
      "disease-overview",
      "nutrition-taiwanese",
      "chest-expansion",
      "resistance-band",
      "oxygen-equipment",
      "diaphragmatic-breathing",
    ],
  },
  {
    id: "program-c",
    title: "組合 C：三合一吸入劑與日常照護",
    subtitle: "聚焦較新的吸入劑示範，搭配營養、痰液清除與氧氣安全。",
    description: "Breztri、Trelegy、Relvar、Anoro、Ultibro、營養、肺復原與氧氣。",
    videoIds: [
      "disease-overview",
      "breztri",
      "trelegy",
      "relvar",
      "anoro",
      "ultibro",
      "acute-exacerbation",
      "nutrition-lung",
      "airway-clearance",
      "diaphragmatic-breathing",
      "pulmonary-rehab",
      "oxygen-equipment",
    ],
  },
  {
    id: "program-d",
    title: "組合 D：復健運動與居家安全",
    subtitle: "適合下午診後段，增加肺復原與居家氧氣照護比例。",
    description: "肺復原運動、呼吸技巧、吸入劑複習、營養與急性警訊。",
    videoIds: [
      "pulmonary-rehab",
      "diaphragmatic-breathing",
      "resistance-band",
      "chest-expansion",
      "airway-clearance",
      "oxygen-equipment",
      "respimat-use",
      "bevespi",
      "trimbow",
      "breztri",
      "acute-exacerbation",
      "nutrition-lung",
    ],
  },
];
